server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432
    username: Hugo
    password: longboards13
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace